### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by 14souta** [14souta/furima-37332#22]
URL |  https://furima-37332.herokuapp.com/
Basic認証のIDとパスワード |   ID: test　　パス： test1234
出品者用のメールアドレスとパスワード |     アドレス：yamataro@tarotaro　パス：taro4649
購入者用のメールアドレスとパスワード | 　アドレス：yamajiroro@jirojiro　パス：jiro4649

**Comment by yusuketono** [comment]
@14souta さん、ご提出ありがとうございます‼︎

> Basic認証のIDとパスワード |   ID: test　　パス： test1234

上記の通りに入力をしましたが、Basic認証が通らないようです。
お手数ですが、IDとパスワードを再度ご確認いただけますでしょうか？

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 14souta** [comment]
id.    sota
パス　　Sota4649

これでいけると思います。

**Comment by yusuketono** [comment]
@14souta さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
「新品・未使用」の項目は2行ではなく、1行で表記しましょう。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by 14souta** [comment]
ご確認ありがとうございます。
修正しましたので再度ご確認よろしくお願いします。

**Comment by snkw-works** [comment]
@14souta さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
**マージやデプロイ忘れの可能性もございます。** 今一度ご確認をお願いします！

[修正依頼箇所]
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう**
「新品・未使用」が別の項目として表示されています。
<img width="399" alt="スクリーンショット_2022-05-25_11_09_23" src="https://user-images.githubusercontent.com/54050089/170164630-c9e3f892-5ba4-415b-804e-484dd97f26d3.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by 14souta** [comment]
すみませんデプロイを忘れていました。
よろしく願いします。

**Comment by snkw-works** [comment]
@14souta さん、フリマアプリ達成要件分の開発お疲れ様でした！
修正が確認でき、正常に動作することが確認できました！ **LGTM** です！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

#### ＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。

また、以下提出物に関するリマインドです。

#### ＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

#### ＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/curriculums/7106

今後の流れに関して、もしご不明点がございましたら、担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/54050089/164166779-9eca4a1e-955a-4d55-bfa3-c0ff25e73e87.png)
